language: java
jdk: oraclejdk11
before_install:
  - chmod +x build.sh
script: ./build.sh
deploy:
  provider: releases
  tag_name: "$TRAVIS_TAG"
  file: "target/Sorting-algorithms-visualized.jar"
  name: "Sorting-algorithms-visualized $TRAVIS_TAG"
  skip_cleanup: true
  api_key:
    secure: "C7jwshJDSEplp0q3Noyu+LU6ZM6NO3lw+D01U3LREt6Njjgv6+kg4XhBxXkcpH/sDqvO1gyRa1JFgBau06QUWgG62wySj4475ctre8PmJne1vnrGEA/rB4+hQ/uwX/mzY58fduuk8YuKGAneH8VmKkmDhloomwaa66C47cPHRJSkfKhA4Aq9Kzf7EVOm8cLn7xuDLI3Yru6BzaKKfpKeM7t+n7lvd4bmpUvTt63w6dx/OhAoH70I3ftZBZHuWneQfVQFeJ2RGhS0WF9aHT4Kics2SOmRj3Usfner/CTKD9ntnLjCKQn+JNasgws/RmWptIFz9cgxqwGlIMu3Xv3UmBF8CfThqD4KCbw3bo0dafbqil21pkUWL8if+QgUhRe7jVseihfZEp+/sDLZfW24W9v9jHVkGI6YjF9dec+hkwxUCu8DazDzbOnSPCJScPw6ctbjOmEVaps4YJBG2LkEEEs2JhhO101j1xW2yP165qTyTiNDwh9YjZ9uiJN1hQnhoV9qq+ZRQwmBmYdaKGFqyTSAY7asaRu8o1wiv6QWAK6q5TwBjdlvTzlHc3QX5zlDZMlVB5QWzW6Iw/CH5OZ9sFbU7Hvo6U7hZAnYxbj4Advqpa+Kdfc+GdlTis5sUc/W+alSJG0P9dJ3S05DQjiIRlMxV6m/fFdYM7u+YNiADN4="
  on:
    tags: true
    repo: "rueno/Sorting-algorithms-visualized"